UPSTREAM_PORT = 59995
DOWNSTREAM_PORT = 59996
PROXY_HOSTNAME = 'halob'

UPSTREAM_URL = 'tcp://%s:%d' % (PROXY_HOSTNAME, UPSTREAM_PORT)
DOWNSTREAM_URL = 'tcp://%s:%d' % (PROXY_HOSTNAME, DOWNSTREAM_PORT)