/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thingm_blinkm_BlinkMUSB */

#ifndef _Included_thingm_blinkm_BlinkMUSB
#define _Included_thingm_blinkm_BlinkMUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thingm_blinkm_BlinkMUSB
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_thingm_blinkm_BlinkMUSB_open
  (JNIEnv *, jobject);

/*
 * Class:     thingm_blinkm_BlinkMUSB
 * Method:    command
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_thingm_blinkm_BlinkMUSB_command
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     thingm_blinkm_BlinkMUSB
 * Method:    setRGB
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_thingm_blinkm_BlinkMUSB_setRGB
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     thingm_blinkm_BlinkMUSB
 * Method:    fadeToRGB
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_thingm_blinkm_BlinkMUSB_fadeToRGB
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     thingm_blinkm_BlinkMUSB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thingm_blinkm_BlinkMUSB_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
